server:
  port: 8761

eureka:
  instance:
    instance-id: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.instance-id}:${server.port}/eureka/

spring:
  application:
    name: sell-eureka-server