server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          username: Han-China
          password: h1728s5388685g
          uri: https://github.com/Han-China/sell-config-center.git
          search-paths: respo
          default-label: master
  application:
    name: config-center